# Generated by Django 4.0.4 on 2022-06-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_address_1_account_address_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
