# Generated by Django 4.0.4 on 2022-06-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_is_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_seller',
            new_name='seller',
        ),
    ]
