# Generated by Django 4.0.4 on 2022-05-31 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_is_seller_account_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='seller',
            new_name='is_seller',
        ),
    ]
