# Generated by Django 4.0.4 on 2022-05-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
