# Generated by Django 4.0.4 on 2022-06-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0014_flashsales'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flashsale',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FlashSales',
        ),
    ]
