# Generated by Django 4.0.4 on 2022-06-09 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0015_product_flashsale_delete_flashsales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flashsale',
        ),
        migrations.CreateModel(
            name='FlashSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.product')),
            ],
        ),
    ]
