# Generated by Django 4.0.4 on 2022-06-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0016_remove_product_flashsale_flashsales'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
