# Generated by Django 4.0.4 on 2022-07-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0022_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashsales',
            options={'verbose_name_plural': 'Flash sales'},
        ),
    ]
