# Generated by Django 4.0.4 on 2022-07-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0027_billing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='user',
        ),
    ]
