# Generated by Django 4.0.4 on 2022-05-31 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0032_rename_is_seller_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='is_seller',
        ),
    ]
