# Generated by Django 4.0.4 on 2022-05-31 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0033_rename_seller_product_is_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_seller',
            new_name='seller',
        ),
    ]
