# Generated by Django 4.0.4 on 2022-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0034_rename_is_seller_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='second_name',
            new_name='other_names',
        ),
        migrations.AddField(
            model_name='billing',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
