# Generated by Django 4.0.4 on 2022-07-13 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0036_billing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='email',
        ),
        migrations.AlterField(
            model_name='billing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
