# Generated by Django 4.0.4 on 2022-07-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0037_remove_billing_email_alter_billing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='user',
        ),
    ]
