# Generated by Django 4.0.4 on 2022-07-09 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
